version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm ci

  pre_build:
    commands:
      - npm run cy:verify
      - npm run cy:info

  build:
    commands:
      - npx cypress run --browser chromium